// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFzs-jaIC6D6lmf1WosyPNtw3C45aQ7ng',
    appId: '1:746294709590:web:38389d59b29fe0fd485af7',
    messagingSenderId: '746294709590',
    projectId: 'projectflutter01-42d89',
    authDomain: 'projectflutter01-42d89.firebaseapp.com',
    storageBucket: 'projectflutter01-42d89.appspot.com',
    measurementId: 'G-HMRRW9X35H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJSzjH2sZ83adDCNqhopYIy8Q7RAdxVA',
    appId: '1:746294709590:android:9c53a5157b36c9da485af7',
    messagingSenderId: '746294709590',
    projectId: 'projectflutter01-42d89',
    storageBucket: 'projectflutter01-42d89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9ABtCEsAX0Hf7KsFQpfNwh6PXWyjc80',
    appId: '1:746294709590:ios:dd8342fd8225757f485af7',
    messagingSenderId: '746294709590',
    projectId: 'projectflutter01-42d89',
    storageBucket: 'projectflutter01-42d89.appspot.com',
    iosBundleId: 'com.example.applicationProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9ABtCEsAX0Hf7KsFQpfNwh6PXWyjc80',
    appId: '1:746294709590:ios:dd8342fd8225757f485af7',
    messagingSenderId: '746294709590',
    projectId: 'projectflutter01-42d89',
    storageBucket: 'projectflutter01-42d89.appspot.com',
    iosBundleId: 'com.example.applicationProject1',
  );
}
